baseURL: "https://fmterrorf.github.io"
languageCode: "en-us"
title: "Daven"
theme: "PaperMod"
params:
    socialIcons:
        - name: github
          url: "https://github.com/fmterrorf"
        - name: linkedin
          url: "https://www.linkedin.com/in/daven-paul-casia/"

