baseURL: "https://fmterrorf.github.io"
languageCode: "en-us"
title: "Daven"
theme: "PaperMod"
params:
    env: production 
    comments: true
    socialIcons:
        - name: github
          url: "https://github.com/fmterrorf"
        - name: linkedin
          url: "https://www.linkedin.com/in/daven-paul-casia/"
    homeInfoParams:
        Content: >
                - I talk about random things that i like to do here 

