baseURL: "https://fmterrorf.github.io"
languageCode: "en-us"
title: "Daven's blog stuff"
theme: "PaperMod"
params:
    homeInfoParams:
        Title: "Welcome to my blog"
        Content: >
                - I talk about random things that i like to do here 

